import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sungsu Park</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Holywater!
        </h1>

        <p className={styles.description}>
          Start enjoying by exploring <a href ="https://github.com/Holllywaterr.com/" className={styles.highlight}><u>Github!</u></a>
        </p>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>Basic Info</h2>
            <p>Birth: 1998.05.21</p>
            <p>City: Seoul</p>
            <p>Country: Republic of Korea</p>
          </a>

          <a className={styles.card}>
          <Image src="/images/face.jpg" alt="Me" width={150} height={200} /> 
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
        </a>
      </footer>
    </div>
  )
}

